<?php
$l['invoice'] = 'Invoice';
$l['reference_no'] = 'Reference';
$l['date_issued'] = 'Billing date';
$l['due_date'] = 'Due date';
$l['from'] = 'Our information';
$l['to'] = 'Billing to';

$l['item_name'] = 'Product';
$l['qty'] = 'Qty';
$l['vat'] = 'VAT';
$l['tax'] = 'Tax';
$l['price'] = 'Price';
$l['discount'] = 'Discount';
$l['total'] = 'Total';
$l['paid'] = 'Paid';
$l['balance_due'] = 'Balance Due';


$l['payment_information'] = 'Payment Information';
$l['notes'] = 'Notes';
$l['partially_paid'] = 'Partially Paid';
$l['fully_paid'] = 'Fully Paid';
$l['not_paid'] = 'Not Paid';
$l['draft'] = 'Draft';
$l['accepted'] = 'Accepted';
$l['declined'] = 'Declined';
$l['pending'] = 'Pending';

$l['page'] = 'Page';
$l['page_of'] = 'of';
$l['valid_until'] = 'Valid Until';