<?php
$l['invoice'] = 'Factura';
$l['estimate'] = 'Estimación';
$l['estimate_cost'] = 'Costo Estimado';
$l['reference_no'] = 'Referencia';
$l['date_issued'] = 'Fecha';
$l['due_date'] = 'Facha de vencimiento';
$l['from'] = 'Nuestra información';
$l['to'] = 'Facturación a';

$l['item_name'] = 'Producto';
$l['amount'] = 'Cantidad';
$l['vat'] = 'Impuestos';
$l['tax'] = 'Impuestos';
$l['price'] = 'Precio';
$l['discount'] = 'Descuento';
$l['total'] = 'Total de';
$l['paid'] = 'Pagado';
$l['balance_due'] = 'Saldo Adeudado';


$l['payment_information'] = 'Información sobre el pago';
$l['notes'] = 'Notas';
$l['partially_paid'] = 'Parcialmente Pagada';
$l['fully_paid'] = 'Totalmente Pagado';
$l['not_paid'] = 'No Pagado';
$l['draft'] = 'Borrador';
$l['accepted'] = 'Aceptado';
$l['declined'] = 'Rehusó';
$l['pending'] = 'Pendiente';

$l['page'] = 'Página';
$l['page_of'] = 'de';

$l['estimate_date'] = 'Estimate Date';
$l['valid_until'] = 'Valid Until';