<?php
$l['invoice'] = 'Facture';
$l['estimate'] = 'Devis';
$l['estimate_cost'] = 'Estimation du coût';
$l['reference_no'] = 'RÉfÉrence';
$l['date_issued'] = 'Date de facturation';
$l['due_date'] = 'Date d\'échéance';
$l['from'] = 'Nos infos';
$l['to'] = 'Facturation à';

$l['item_name'] = 'Produit';
$l['amount'] = 'Montant';
$l['vat'] = 'Cuve';
$l['tax'] = 'Taxe';
$l['price'] = 'Prix';
$l['discount'] = 'Réduction';
$l['total'] = 'Total';
$l['paid'] = 'Payé';
$l['balance_due'] = 'Solde dû';


$l['payment_information'] = 'Informations de paiement';
$l['notes'] = 'Notes';
$l['partially_paid'] = 'Paiement partiel';
$l['fully_paid'] = 'Payé';
$l['not_paid'] = 'Impayé';
$l['draft'] = 'Brouillon';
$l['accepted'] = 'Accepté';
$l['declined'] = 'Refusé';
$l['pending'] = 'En cours';

$l['page'] = 'Page';
$l['page_of'] = 'de';

$l['estimate_date'] = 'Estimate Date';
$l['valid_until'] = 'Valid Until';