<?php
$l['invoice'] = 'Fattura';
$l['estimate'] = 'Stima';
$l['estimate_cost'] = 'Stima Dei Costi';
$l['reference_no'] = 'Riferimento';
$l['date_issued'] = 'Data di fatturazione';
$l['due_date'] = 'Scadenza';
$l['from'] = 'Nostre informazioni';
$l['to'] = 'Fatturazione per';

$l['item_name'] = 'Prodotto';
$l['amount'] = 'Quantità';
$l['vat'] = 'Imposta';
$l['tax'] = 'Tasse';
$l['price'] = 'Prezzo';
$l['discount'] = 'Sconto';
$l['total'] = 'Totale';
$l['paid'] = 'Pagato';
$l['balance_due'] = 'Saldo scaduto';


$l['payment_information'] = 'Informazioni Sul Pagamento';
$l['notes'] = 'Note';
$l['partially_paid'] = 'Parzialmente Pagato';
$l['fully_paid'] = 'Pagato';
$l['not_paid'] = 'Non Pagato';
$l['draft'] = 'Bozza';
$l['accepted'] = 'Accettato';
$l['declined'] = 'Rifiutato';
$l['pending'] = 'In Attesa';

$l['page'] = 'Pagina';
$l['page_of'] = 'di';

$l['estimate_date'] = 'Estimate Date';
$l['valid_until'] = 'Valid Until';