<?php
$l['invoice'] = 'Factuur';
$l['estimate'] = 'Schatting';
$l['estimate_cost'] = 'Geschatte Kosten';
$l['reference_no'] = 'Referentie';
$l['date_issued'] = 'Aangemaakt';
$l['due_date'] = 'Vervaldatum';
$l['from'] = 'Onze gegevens';
$l['to'] = 'Begunstige';

$l['item_name'] = 'Product';
$l['amount'] = 'Aantal';
$l['vat'] = 'BTW';
$l['tax'] = 'Belasting';
$l['price'] = 'Prijs';
$l['discount'] = 'Korting';
$l['total'] = 'Totaal';
$l['paid'] = 'Betaald';
$l['balance_due'] = 'Saldo';

$l['payment_information'] = 'Betaling informatie';
$l['notes'] = 'Notities';
$l['partially_paid'] = 'Deels betaald';
$l['fully_paid'] = 'Betaald';
$l['not_paid'] = 'Betaling niet ontvangen';
$l['draft'] = 'Concept';
$l['accepted'] = 'Geacepteerd';
$l['declined'] = 'Geweigerd';
$l['pending'] = 'In afwachting';

$l['page'] = 'Pagina';
$l['page_of'] = 'van de';

$l['estimate_date'] = 'Estimate Date';
$l['valid_until'] = 'Valid Until';